keybinding:
  universal:
    scrollUpMain: '<c-y>'
    scrollDownMain: '<c-e>'
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
